# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: AsuraaLibrary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build: 
        name: AsuraaLibrary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-dotnet@v3

            - name: Initialize Python 3.9
              uses: actions/setup-python@v4
              with:
                python-version: 3.9
            - name: Setup Node.js 20 (optional, not necessary)
              uses: actions/setup-node@v3
              with:
                node-version: '20'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8
         
            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings.
                flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
            - name: Build binary wheel and a source tarball
              run: python setup.py sdist
              
            - name: Publish distribution to PyPI
              uses: pypa/gh-action-pypi-publish@unstable/v1
              with:
               password: ${{ secrets.PYPI_API_TOKEN }}

              
